version: v1.0.0
steps:
  - cmd: >-
      {{.Run.Registry}}/buildx
      build --push
      -t {{.Run.Registry}}/{{.Values.REPOSITORY_NAME}}:{{.Run.ID}}
      --cache-from={{.Run.Registry}}/{{.Values.REPOSITORY_NAME}}:cache
      --cache-to=type=registry,ref={{.Run.Registry}}/{{.Values.REPOSITORY_NAME}}:cache,mode=max
      {{.Values.BUILD_CONTEXT}}
